### PR TITLE
change eu config values to reflect output power

### PR DESCRIPTION
**Pull request by refugeesus**
Change values in EU868 config file to reflect output power designated by the key.

### CODE REVIEW

**Comment by Vagabond** [comment]
@JayKickliter can we land this, perhaps?

**Comment by refugeesus** [comment]
I increased the rssi and snr output value resolution to 3 decimal places and stopped rounding rssi. We round and clip to one decimal place currently. A float is currently supported in proto and miner takes a generic `number()` type so upstream shouldn't see this value any differently.

**Comment by JayKickliter** [comment]
@Vagabond we _could_, but that last commit is unrelated. @refugeesus If we do need that last commit, `TX_BUFF_SIZE` should be increased by however many characters the new format specifiers would allow.

**Review by JayKickliter — APPROVED** [review]

**Comment by JayKickliter** [comment]
I reverted my approval just to make sure this config doesn't start being used before checking that it works.

**Comment by JayKickliter** [comment]
Closing as this PR was superceded by #12

**Pull request closed without merging**
